name: Inter-branch merge workflow
on:
  push:
    branches:
      - release/**

permissions:
  contents: write
  pull-requests: write

jobs:
  Merge:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@e9208a724ccace0ffb8dcc119f03a3d1968e6232 # 2024-06-24
